---
# tasks file for redash
- name: create redash user
  user: name={{ redash_user }}

- name: create redash data dir
  file: state=directory path={{ redash_home }} owner={{ redash_user }} recurse=true

- name: copy docker-compose
  template: dest="{{ redash_home }}/docker-compose.yml" owner={{ redash_user }}  src=docker-compose.yml.j2
  notify: rebuild redash

- name: copy env file
  template: dest="{{ redash_home }}/env" owner={{ redash_user }} src=env.j2
  notify: rebuild redash

- name: get actual docker-entrypoint file
  get_url:
    url: https://raw.githubusercontent.com/getredash/redash/{{ redash_branch }}/bin/docker-entrypoint
    dest: "{{ redash_home }}/docker-entrypoint"
    mode: 0755
    force: yes

- name: copy systemd unit
  template: src="redash.service.j2" dest="/etc/systemd/system/redash.service"

- name: start the service
  systemd: name=redash enabled=yes state=restarted daemon_reload=yes