---
# handlers file for redash
- name: rebuild redash
  command: /usr/local/bin/docker-compose build chdir={{ redash_home }}
  notify: initialise redash

- name: restart redash
  systemd:
    state: restarted 
    name: redash

- name: initialise redash
  command: /usr/local/bin/docker-compose run --rm server create_db chdir={{ redash_home }}
  ignore_errors: yes
  notify:
    - restart redash
